import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {ActivityStore} from '../src/activity.js';
function req({ua='agent-client',ip='203.0.113.10',source,referer}={}){return {method:'POST',url:'/mcp',headers:{'user-agent':ua,'x-forwarded-for':ip,...(source?{'x-preflight-source':source}:{}),...(referer?{referer}:{})},socket:{remoteAddress:ip}}}
test('activity counts outside calls and unique callers',()=>{const a=new ActivityStore();a.record(req(),{kind:'check',route:'HTTP',target:'https://example.com'});a.record(req({ip:'203.0.113.11'}),{kind:'mcp',route:'tools/call:preflight_check'});const s=a.snapshot();assert.equal(s.external.callsToday,2);assert.equal(s.external.uniqueCallersToday,2);assert.equal(s.feed.length,2)});
test('activity filters identifiable CI/test traffic',()=>{const a=new ActivityStore();a.record(req({ua:'curl/8.0'}),{kind:'check',target:'https://example.com'});a.record(req({ua:'real-agent'}),{kind:'check',target:'https://example.org'});assert.equal(a.snapshot().external.callsToday,1)});
test('activity does not expose raw caller addresses',()=>{const a=new ActivityStore();a.record(req({ip:'198.51.100.42'}),{kind:'check',target:'https://example.com'});const e=a.snapshot().feed[0];assert.notEqual(e.caller,'198.51.100.42');assert.equal(e.caller.length,12)});
test('demo and unattributed real-world use do not earn stranger milestone',()=>{const a=new ActivityStore();a.record(req(),{kind:'check',target:'https://example.com'});a.record(req({ip:'203.0.113.22'}),{kind:'check',target:'https://developer.mozilla.org/docs/Web'});const s=a.snapshot();assert.equal(s.realUse.allTimeDemoCalls,1);assert.equal(s.realUse.allTimeRealWorldCalls,1);assert.equal(s.realUse.allTimeVerifiedStrangers,0);assert.equal(s.realWorldConversionMilestones[0].achieved,false)});
test('known validator never earns a true stranger box',()=>{const a=new ActivityStore();const r=req({ip:'203.0.113.70',ua:'mcp-verifier'});a.record(r,{kind:'mcp',route:'tools/list'});a.record(r,{kind:'mcp',route:'tools/call:preflight_check',target:'https://developer.mozilla.org'});const s=a.snapshot();assert.equal(s.realUse.allTimeVerifiedStrangers,0);assert.equal(s.candidateRealUse[0].classification,'KNOWN_VALIDATOR')});
test('generic fast discovery followed by preflight_check is only likely validator',()=>{const a=new ActivityStore();const r=req({ip:'203.0.113.71',ua:'real-mcp-agent'});a.record(r,{kind:'mcp',route:'tools/list'});a.record(r,{kind:'mcp',route:'tools/call:preflight_check',target:'https://developer.mozilla.org/docs/Web'});const s=a.snapshot();assert.equal(s.realUse.allTimeVerifiedStrangers,0);assert.equal(s.candidateRealUse[0].classification,'LIKELY_VALIDATOR')});
test('interactive MCP client identity supports credible stranger classification',()=>{const a=new ActivityStore();const r=req({ip:'203.0.113.72',ua:'modelcontextprotocol-client'});a.record(r,{kind:'mcp',route:'initialize',clientInfo:{name:'Cursor',version:'2.0'}});a.record(r,{kind:'mcp',route:'tools/call:preflight_check',target:'https://developer.mozilla.org/docs/Web'});const s=a.snapshot();assert.equal(s.realUse.allTimeVerifiedStrangers,1);assert.equal(s.realWorldConversionMilestones[0].achieved,true);assert.equal(s.realWorldConversionMilestones[0].classification,'CREDIBLE_REAL_USE')});
test('referred REST real-world check can support credible use',()=>{const a=new ActivityStore();const r=req({ip:'203.0.113.73',referer:'https://agent.example/app'});a.record(r,{kind:'check',target:'https://developer.mozilla.org/docs/Web'});const s=a.snapshot();assert.equal(s.realUse.allTimeVerifiedStrangers,1);assert.equal(s.realWorldConversionMilestones[0].achieved,true)});
test('permanent ledger downgrades historical unaudited event instead of inventing stranger',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'preflight-activity-'));try{fs.writeFileSync(path.join(dir,'real-use.json'),JSON.stringify({version:1,events:[{id:'old',at:new Date().toISOString(),kind:'mcp',route:'tools/call:preflight_check',external:true,caller:'358d3660abcd',source:'mcp-client',channel:'mcp',host:'example.org'}]}));const a=new ActivityStore({dataDir:dir});const s=a.snapshot();assert.equal(s.realUse.allTimeVerifiedStrangers,0);assert.equal(s.candidateRealUse[0].classification,'UNKNOWN_MACHINE');assert.match(s.candidateRealUse[0].reasons[0],/historical/i)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
