import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,VERSION} from '../src/server.js';

class MemoryCache{constructor(){this.m=new Map()}async get(k){const v=this.m.get(k);return v?{...v,cache:{hit:true}}:null}async put(k,v){this.m.set(k,v);return {...v,cache:{hit:false}}}}
class MemoryFeedback{
 constructor(){this.rows=[]}
 async record(row){this.rows.push(row);return {feedbackId:'test-feedback',accepted:true,urlHash:'abc',domainHash:'def'}}
 async evidence(url){const routes={};for(const r of ['HTTP','BROWSER','MACHINE_ENDPOINT','AVOID']){const hits=this.rows.filter(x=>x.url===url&&x.route===r),success=hits.filter(x=>x.outcome==='success').length,failure=hits.length-success;routes[r]={success,failure,total:hits.length,successRate:hits.length?success/hits.length:null,avgLatencyMs:null};}return {url:{samples:this.rows.length,routes},domain:{samples:0,routes:{HTTP:{success:0,failure:0,total:0,successRate:null,avgLatencyMs:null},BROWSER:{success:0,failure:0,total:0,successRate:null,avgLatencyMs:null},MACHINE_ENDPOINT:{success:0,failure:0,total:0,successRate:null,avgLatencyMs:null},AVOID:{success:0,failure:0,total:0,successRate:null,avgLatencyMs:null}}}}}
}
async function withServer(fn,{probe=async url=>({url,reachable:true,status:200,bestRoute:'HTTP',reason:'test',confidence:.7}),feedbackStore=new MemoryFeedback()}={}){const s=createServer({cacheStore:new MemoryCache(),probe,feedbackStore});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await fn(`http://127.0.0.1:${s.address().port}`,feedbackStore)}finally{await new Promise(r=>s.close(r))}}

test('health and version endpoints',()=>withServer(async base=>{let r=await fetch(base+'/health');assert.equal(r.status,200);assert.equal((await r.json()).version,VERSION);r=await fetch(base+'/version');assert.equal((await r.json()).service,'PREFLIGHT')}));

test('check requires a URL',()=>withServer(async base=>{const r=await fetch(base+'/v1/check');assert.equal(r.status,400);assert.equal((await r.json()).code,'PREFLIGHT_BAD_REQUEST')}));

test('check probes once then serves cached answer',()=>{let calls=0;return withServer(async base=>{const url=encodeURIComponent('https://example.com/a');let r=await fetch(`${base}/v1/check?url=${url}`);assert.equal(r.headers.get('x-preflight-cache'),'MISS');let j=await r.json();assert.equal(j.bestRoute,'HTTP');assert.equal(j.cache.hit,false);r=await fetch(`${base}/v1/check?url=${url}`);assert.equal(r.headers.get('x-preflight-cache'),'HIT');j=await r.json();assert.equal(j.cache.hit,true);assert.equal(calls,1);},{probe:async url=>{calls++;return {url,reachable:true,status:200,bestRoute:'HTTP',reason:'test',confidence:.7}}})});

test('feedback endpoint validates and accepts route outcomes',()=>withServer(async(base,store)=>{let r=await fetch(base+'/v1/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:'https://example.com/a',route:'BROWSER',outcome:'success',latencyMs:850})});assert.equal(r.status,202);let j=await r.json();assert.equal(j.accepted,true);assert.equal(store.rows.length,1);r=await fetch(base+'/v1/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:'https://example.com/a',route:'MAGIC',outcome:'success'})});assert.equal(r.status,400);assert.equal((await r.json()).code,'PREFLIGHT_BAD_FEEDBACK')}));

test('new feedback changes even a cached recommendation after threshold',()=>withServer(async(base)=>{const target='https://example.com/a',q=encodeURIComponent(target);let r=await fetch(`${base}/v1/check?url=${q}`);assert.equal((await r.json()).bestRoute,'HTTP');for(let i=0;i<5;i++)await fetch(base+'/v1/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:target,route:'BROWSER',outcome:'success'})});r=await fetch(`${base}/v1/check?url=${q}`);assert.equal(r.headers.get('x-preflight-cache'),'HIT');const j=await r.json();assert.equal(j.bestRoute,'BROWSER');assert.equal(j.feedback.applied,true);}));

test('MCP initialize and tools/list advertise PREFLIGHT tools',()=>withServer(async base=>{let r=await fetch(base+'/mcp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}}})});assert.equal(r.status,200);let j=await r.json();assert.equal(j.result.serverInfo.name,'PREFLIGHT');assert.equal(r.headers.get('mcp-protocol-version'),'2025-11-25');r=await fetch(base+'/mcp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/list',params:{}})});j=await r.json();assert.deepEqual(j.result.tools.map(x=>x.name),['preflight_check','preflight_feedback']);}));

test('MCP preflight_check calls routing engine',()=>withServer(async base=>{const r=await fetch(base+'/mcp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'preflight_check',arguments:{url:'https://example.com/a'}}})});assert.equal(r.status,200);const j=await r.json();assert.equal(j.result.structuredContent.bestRoute,'HTTP');assert.equal(j.result.isError,undefined);}));

test('MCP initialized notification returns 202',()=>withServer(async base=>{const r=await fetch(base+'/mcp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized',params:{}})});assert.equal(r.status,202);assert.equal(await r.text(),'');}));
