import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const MAX_EVENTS=5000;
const BOT_TEST_RE=/(github-actions|preflight-registry-check|curl|railway|healthcheck)/i;
const DEMO_HOSTS=new Set(['example.com','www.example.com']);
const DISCOVERY_ROUTES=new Set(['initialize','notifications/initialized','tools/list','ping','resources/list','resources/templates/list','prompts/list','completion/complete','logging/setLevel']);
function defaultDataDir(){return process.env.PREFLIGHT_DATA_DIR??(process.env.RAILWAY_ENVIRONMENT?'/data':path.resolve('.preflight-data'));}
function day(ts){return new Date(ts).toISOString().slice(0,10)}
function hash(value){return crypto.createHash('sha256').update(String(value||'unknown')).digest('hex').slice(0,12)}
function safeLabel(value,max=64){return String(value||'').replace(/[^a-zA-Z0-9._:/-]/g,'').slice(0,max)||null}
function referrerHost(req){try{return new URL(String(req.headers.referer||req.headers.referrer||'')).host||null}catch{return null}}
function source(req){const ua=String(req.headers['user-agent']||'unknown');const explicit=String(req.headers['x-preflight-source']||'').trim();if(explicit)return safeLabel(explicit);if(/modelcontextprotocol|mcp/i.test(ua))return 'mcp-client';if(/github/i.test(ua))return 'github';return 'direct';}
function channel(req,kind){if(kind==='mcp')return 'mcp';if(req.headers['x-preflight-source'])return 'tagged-rest';if(referrerHost(req))return 'referred-rest';return 'rest'}
function internal(req){const ua=String(req.headers['user-agent']||'');return String(req.headers['x-preflight-internal']||'')==='1'||BOT_TEST_RE.test(ua)}
function isDiscoveryRoute(route){return DISCOVERY_ROUTES.has(String(route||''))}
function realUse(e){if(!e.external)return false;if(e.kind==='check'||e.kind==='feedback')return true;if(e.kind==='mcp'&&String(e.route||'').startsWith('tools/call'))return true;return false}
function useClass(e){if(!realUse(e))return null;if(e.kind==='check'&&DEMO_HOSTS.has(String(e.host||'').toLowerCase()))return 'demo';return 'real-world'}
export class ActivityStore{
 constructor({dataDir=null}={}){this.dataDir=dataDir??defaultDataDir();this.file=path.join(this.dataDir,'activity.json');this.persistent=Boolean(dataDir||process.env.PREFLIGHT_DATA_DIR||process.env.RAILWAY_ENVIRONMENT);this.events=[];this.firstSeen=new Map();this.discoverySeen=new Map();if(this.persistent)this.load()}
 load(){if(!this.persistent)return;try{const d=JSON.parse(fs.readFileSync(this.file,'utf8'));this.events=Array.isArray(d.events)?d.events.slice(0,MAX_EVENTS):[];this.firstSeen=new Map(Array.isArray(d.firstSeen)?d.firstSeen:[]);this.discoverySeen=new Map(Array.isArray(d.discoverySeen)?d.discoverySeen:[])}catch(e){if(e?.code!=='ENOENT')console.error('activity load failed',e?.message)}}
 persist(){if(!this.persistent)return;try{fs.mkdirSync(this.dataDir,{recursive:true});const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify({events:this.events,firstSeen:[...this.firstSeen],discoverySeen:[...this.discoverySeen]}),{mode:0o600});fs.renameSync(tmp,this.file)}catch(e){console.error('activity persist failed',e?.message)}}
 record(req,{kind,route=null,target=null,status=200}={}){const now=Date.now();const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();const fingerprint=[forwarded||req.socket?.remoteAddress||'',req.headers['user-agent']||'',req.headers['accept-language']||''].join('|');const caller=hash(fingerprint);const seen=this.firstSeen.get(caller);if(!seen)this.firstSeen.set(caller,now);const isDiscovery=kind==='mcp'&&isDiscoveryRoute(route);if(isDiscovery&&!this.discoverySeen.has(caller))this.discoverySeen.set(caller,now);const event={id:crypto.randomUUID(),at:new Date(now).toISOString(),kind,route,status,source:source(req),channel:channel(req,kind),referrerHost:referrerHost(req),campaign:safeLabel(req.headers['x-preflight-campaign']),caller,callerState:seen?'returning':'new',external:!internal(req),discovery:isDiscovery,convertedFromDiscovery:!isDiscovery&&this.discoverySeen.has(caller)};if(target){try{event.host=new URL(target).host}catch{}}event.realUse=realUse(event);event.useClass=useClass(event);this.events.unshift(event);if(this.events.length>MAX_EVENTS)this.events.length=MAX_EVENTS;this.persist();return event}
 snapshot(){const today=day(Date.now());const all=this.events;const external=all.filter(e=>e.external);const todays=external.filter(e=>e.at.slice(0,10)===today);const real=external.filter(realUse).map(e=>({...e,useClass:e.useClass||useClass(e)})),realToday=real.filter(e=>e.at.slice(0,10)===today);const demoToday=realToday.filter(e=>e.useClass==='demo'),worldToday=realToday.filter(e=>e.useClass==='real-world');const discoveries=todays.filter(e=>e.kind==='mcp'&&isDiscoveryRoute(e.route));const converted=realToday.filter(e=>e.convertedFromDiscovery);const bySource=Object.entries(todays.reduce((a,e)=>{a[e.source]=(a[e.source]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).map(([source,calls])=>({source,calls}));const byChannel=Object.entries(todays.reduce((a,e)=>{a[e.channel]=(a[e.channel]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).map(([channel,calls])=>({channel,calls}));return {service:'PREFLIGHT',generatedAt:new Date().toISOString(),external:{callsToday:todays.length,uniqueCallersToday:new Set(todays.map(e=>e.caller)).size,mcpCallsToday:todays.filter(e=>e.kind==='mcp').length,checksToday:todays.filter(e=>e.kind==='check').length,feedbackToday:todays.filter(e=>e.kind==='feedback').length,lastCall:external[0]?.at||null},realUse:{achieved:real.length>0,callsToday:realToday.length,uniqueCallersToday:new Set(realToday.map(e=>e.caller)).size,newCallersToday:new Set(realToday.filter(e=>e.callerState==='new').map(e=>e.caller)).size,returningCallersToday:new Set(realToday.filter(e=>e.callerState==='returning').map(e=>e.caller)).size,demoCallsToday:demoToday.length,demoCallersToday:new Set(demoToday.map(e=>e.caller)).size,realWorldCallsToday:worldToday.length,realWorldCallersToday:new Set(worldToday.map(e=>e.caller)).size,firstAt:real.length?real[real.length-1].at:null,lastAt:real[0]?.at||null},conversion:{discoveryCallsToday:discoveries.length,discoveryCallersToday:new Set(discoveries.map(e=>e.caller)).size,convertedCallsToday:converted.length,convertedCallersToday:new Set(converted.map(e=>e.caller)).size},attribution:{bySource,byChannel},persistence:{enabled:this.persistent,file:this.persistent?this.file:null,eventCapacity:MAX_EVENTS},privacy:{rawIpStored:false,fullTargetUrlStored:false,callerId:'short one-way request fingerprint hash; operational only'},all:{callsToday:all.filter(e=>e.at.slice(0,10)===today).length},realFeed:real.slice(0,100),checkFeed:external.filter(e=>e.kind==='check').map(e=>({...e,useClass:e.useClass||useClass(e)})).slice(0,100),feed:external.slice(0,50)}}
}
