import crypto from 'node:crypto';

const MAX_EVENTS=5000;
const BOT_TEST_RE=/(github-actions|preflight-registry-check|curl|railway|healthcheck)/i;
const DISCOVERY_ROUTES=new Set(['initialize','notifications/initialized','tools/list','ping']);
function day(ts){return new Date(ts).toISOString().slice(0,10)}
function hash(value){return crypto.createHash('sha256').update(String(value||'unknown')).digest('hex').slice(0,12)}
function safeLabel(value,max=64){return String(value||'').replace(/[^a-zA-Z0-9._:/-]/g,'').slice(0,max)||null}
function referrerHost(req){try{return new URL(String(req.headers.referer||req.headers.referrer||'')).host||null}catch{return null}}
function source(req){const ua=String(req.headers['user-agent']||'unknown');const explicit=String(req.headers['x-preflight-source']||'').trim();if(explicit)return safeLabel(explicit);if(/modelcontextprotocol|mcp/i.test(ua))return 'mcp-client';if(/github/i.test(ua))return 'github';return 'direct';}
function channel(req,kind){if(kind==='mcp')return 'mcp';if(req.headers['x-preflight-source'])return 'tagged-rest';if(referrerHost(req))return 'referred-rest';return 'rest'}
function internal(req){const ua=String(req.headers['user-agent']||'');return String(req.headers['x-preflight-internal']||'')==='1'||BOT_TEST_RE.test(ua)}
function realUse(e){if(!e.external)return false;if(e.kind==='check'||e.kind==='feedback')return true;if(e.kind==='mcp'&&!DISCOVERY_ROUTES.has(String(e.route||'')))return true;return false}
export class ActivityStore{
 constructor(){this.events=[];this.firstSeen=new Map();this.discoverySeen=new Map()}
 record(req,{kind,route=null,target=null,status=200}={}){const now=Date.now();const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();const fingerprint=[forwarded||req.socket?.remoteAddress||'',req.headers['user-agent']||'',req.headers['accept-language']||''].join('|');const caller=hash(fingerprint);const seen=this.firstSeen.get(caller);if(!seen)this.firstSeen.set(caller,now);const isDiscovery=kind==='mcp'&&DISCOVERY_ROUTES.has(String(route||''));if(isDiscovery&&!this.discoverySeen.has(caller))this.discoverySeen.set(caller,now);const event={id:crypto.randomUUID(),at:new Date(now).toISOString(),kind,route,status,source:source(req),channel:channel(req,kind),referrerHost:referrerHost(req),campaign:safeLabel(req.headers['x-preflight-campaign']),caller,callerState:seen?'returning':'new',external:!internal(req),discovery:isDiscovery,convertedFromDiscovery:!isDiscovery&&this.discoverySeen.has(caller)};if(target){try{event.host=new URL(target).host}catch{}}event.realUse=realUse(event);this.events.unshift(event);if(this.events.length>MAX_EVENTS)this.events.length=MAX_EVENTS;return event}
 snapshot(){const today=day(Date.now());const all=this.events;const external=all.filter(e=>e.external);const todays=external.filter(e=>e.at.slice(0,10)===today);const real=external.filter(realUse),realToday=real.filter(e=>e.at.slice(0,10)===today);const discoveries=todays.filter(e=>e.discovery);const converted=realToday.filter(e=>e.convertedFromDiscovery);const bySource=Object.entries(todays.reduce((a,e)=>{a[e.source]=(a[e.source]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).map(([source,calls])=>({source,calls}));const byChannel=Object.entries(todays.reduce((a,e)=>{a[e.channel]=(a[e.channel]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).map(([channel,calls])=>({channel,calls}));return {service:'PREFLIGHT',generatedAt:new Date().toISOString(),external:{callsToday:todays.length,uniqueCallersToday:new Set(todays.map(e=>e.caller)).size,mcpCallsToday:todays.filter(e=>e.kind==='mcp').length,checksToday:todays.filter(e=>e.kind==='check').length,feedbackToday:todays.filter(e=>e.kind==='feedback').length,lastCall:external[0]?.at||null},realUse:{achieved:real.length>0,callsToday:realToday.length,uniqueCallersToday:new Set(realToday.map(e=>e.caller)).size,newCallersToday:new Set(realToday.filter(e=>e.callerState==='new').map(e=>e.caller)).size,returningCallersToday:new Set(realToday.filter(e=>e.callerState==='returning').map(e=>e.caller)).size,firstAt:real.length?real[real.length-1].at:null,lastAt:real[0]?.at||null},conversion:{discoveryCallsToday:discoveries.length,discoveryCallersToday:new Set(discoveries.map(e=>e.caller)).size,convertedCallsToday:converted.length,convertedCallersToday:new Set(converted.map(e=>e.caller)).size},attribution:{bySource,byChannel},privacy:{rawIpStored:false,fullTargetUrlStored:false,callerId:'short salted-like request fingerprint hash; operational only'},all:{callsToday:all.filter(e=>e.at.slice(0,10)===today).length},feed:external.slice(0,50)}}
}
