import http from 'node:http';
import crypto from 'node:crypto';
import {createUrlCache} from './cache.js';
import {probeUrl} from './probe.js';
import {FeedbackStore,applyRouteFeedback,ROUTES,OUTCOMES} from './feedback.js';
import {handleMcpMessage,MCP_PROTOCOL_VERSION} from './mcp.js';
import {ActivityStore} from './activity.js';

export const VERSION='0.7.0';
const cache=createUrlCache();
const feedback=new FeedbackStore();
const activity=new ActivityStore();
const baseHeaders={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','cache-control':'no-store'};
function send(res,status,body,headers={}){const json=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(json),...baseHeaders,...headers});res.end(json)}
function sendHtml(res,status,html){res.writeHead(status,{'content-type':'text/html; charset=utf-8','content-length':Buffer.byteLength(html),...baseHeaders});res.end(html)}
function keyFor(url){const u=new URL(url);u.hash='';return u.href;}
async function readJson(req,maxBytes=16384){let total=0,chunks=[];for await(const chunk of req){total+=chunk.length;if(total>maxBytes)throw Object.assign(new Error('Request body too large'),{code:'PREFLIGHT_BODY_TOO_LARGE'});chunks.push(chunk);}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON body'),{code:'PREFLIGHT_BAD_JSON'})}}
function validateFeedback(body){if(!body||typeof body!=='object')throw Object.assign(new Error('Feedback body is required'),{code:'PREFLIGHT_BAD_FEEDBACK'});let u;try{u=new URL(body.url)}catch{throw Object.assign(new Error('Invalid feedback URL'),{code:'PREFLIGHT_BAD_FEEDBACK'})}if(!['http:','https:'].includes(u.protocol))throw Object.assign(new Error('Feedback URL must be http/https'),{code:'PREFLIGHT_BAD_FEEDBACK'});if(!ROUTES.includes(body.route))throw Object.assign(new Error(`route must be one of ${ROUTES.join(', ')}`),{code:'PREFLIGHT_BAD_FEEDBACK'});if(!OUTCOMES.includes(body.outcome))throw Object.assign(new Error(`outcome must be one of ${OUTCOMES.join(', ')}`),{code:'PREFLIGHT_BAD_FEEDBACK'});const latencyMs=body.latencyMs==null?null:Number(body.latencyMs);if(latencyMs!=null&&(!Number.isFinite(latencyMs)||latencyMs<0||latencyMs>300000))throw Object.assign(new Error('latencyMs must be between 0 and 300000'),{code:'PREFLIGHT_BAD_FEEDBACK'});return {url:u.href,route:body.route,outcome:body.outcome,latencyMs};}
function feedbackAuthorized(req,key){if(!key)return true;const auth=String(req.headers.authorization||'');const supplied=auth.startsWith('Bearer ')?auth.slice(7):'';if(!supplied||supplied.length!==key.length)return false;return crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(key));}
function validOrigin(req){const origin=req.headers.origin;if(!origin)return true;try{const o=new URL(origin);const host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();return o.host===host;}catch{return false;}}
function dashboardHtml(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PREFLIGHT Activity</title><style>body{font-family:system-ui,-apple-system,sans-serif;background:#0b1020;color:#eef2ff;margin:0;padding:32px}.wrap{max-width:1050px;margin:auto}.top{display:flex;justify-content:space-between;align-items:end;gap:20px;flex-wrap:wrap}.muted{color:#9ca3af}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px;margin:26px 0}.card{background:#151b2f;border:1px solid #28304d;border-radius:16px;padding:18px}.n{font-size:34px;font-weight:800}.feed{background:#11172a;border-radius:16px;overflow:hidden;border:1px solid #28304d}.row{display:grid;grid-template-columns:180px 150px 1fr 120px;gap:10px;padding:12px 16px;border-top:1px solid #222a43}.row:first-child{border-top:0}.ok{color:#79f2a7}.empty{padding:24px;color:#9ca3af}@media(max-width:720px){body{padding:18px}.row{grid-template-columns:1fr}.hide-mobile{display:none}}</style></head><body><div class="wrap"><div class="top"><div><h1>PREFLIGHT Activity</h1><div class="muted">Real outside usage only. CI/health/test traffic is filtered when identifiable.</div></div><div class="muted" id="updated">Loading…</div></div><div class="grid"><div class="card"><div class="muted">External calls today</div><div class="n" id="calls">—</div></div><div class="card"><div class="muted">Unique callers today</div><div class="n" id="unique">—</div></div><div class="card"><div class="muted">MCP calls today</div><div class="n" id="mcp">—</div></div><div class="card"><div class="muted">URL checks today</div><div class="n" id="checks">—</div></div></div><h2>External activity feed</h2><div class="feed" id="feed"><div class="empty">No external activity recorded yet.</div></div></div><script>async function load(){try{const r=await fetch('/v1/activity');const d=await r.json();document.getElementById('calls').textContent=d.external.callsToday;document.getElementById('unique').textContent=d.external.uniqueCallersToday;document.getElementById('mcp').textContent=d.external.mcpCallsToday;document.getElementById('checks').textContent=d.external.checksToday;document.getElementById('updated').textContent='Updated '+new Date(d.generatedAt).toLocaleTimeString();const f=document.getElementById('feed');if(!d.feed.length){f.innerHTML='<div class="empty">No external activity recorded yet.</div>';return}f.innerHTML=d.feed.map(e=>'<div class="row"><div>'+new Date(e.at).toLocaleString()+'</div><div class="ok">'+e.kind+'</div><div>'+(e.host||e.route||'—')+'</div><div>'+e.source+'</div></div>').join('')}catch(e){document.getElementById('updated').textContent='Unable to load activity'}}load();setInterval(load,15000)</script></body></html>`}

export function createServer({cacheStore=cache,probe=probeUrl,feedbackStore=feedback,feedbackKey=process.env.PREFLIGHT_FEEDBACK_KEY||'',activityStore=activity}={}){
 async function check(target){let key;try{key=keyFor(target)}catch{throw Object.assign(new Error('Invalid URL'),{code:'PREFLIGHT_BAD_URL'})}const hit=await cacheStore.get(key);if(hit){const evidence=await feedbackStore.evidence(target);return applyRouteFeedback(hit,evidence);}const result=await probe(target);const stored=await cacheStore.put(key,result);const evidence=await feedbackStore.evidence(target);return applyRouteFeedback(stored,evidence);}
 async function recordFeedback(body){const valid=validateFeedback(body);const receipt=await feedbackStore.record(valid);const evidence=await feedbackStore.evidence(valid.url);return {...receipt,evidence};}
 return http.createServer(async(req,res)=>{res.setHeader('x-request-id',req.headers['x-request-id']||crypto.randomUUID());const u=new URL(req.url,'http://preflight.local');try{
   if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'PREFLIGHT',version:VERSION});
   if(req.method==='GET'&&u.pathname==='/ready'){const state=await feedbackStore.ready();return send(res,200,{ready:true,service:'PREFLIGHT',version:VERSION,persistence:state.ok?'writable':'unknown',feedbackProtection:feedbackKey?'bearer':'open'});}
   if(req.method==='GET'&&u.pathname==='/version')return send(res,200,{service:'PREFLIGHT',version:VERSION});
   if(req.method==='GET'&&u.pathname==='/activity')return sendHtml(res,200,dashboardHtml());
   if(req.method==='GET'&&u.pathname==='/v1/activity')return send(res,200,activityStore.snapshot());
   if(req.method==='GET'&&u.pathname==='/')return send(res,200,{name:'PREFLIGHT',version:VERSION,tagline:'Before your AI agent visits a URL, ask us how to get there.',check:'GET /v1/check?url=https://example.com',feedback:'POST /v1/feedback',mcp:'POST /mcp',activity:'GET /activity',routes:ROUTES});
   if(u.pathname==='/mcp'){
     if(!validOrigin(req))return send(res,403,{error:'Origin not allowed',code:'PREFLIGHT_BAD_ORIGIN'});
     if(req.method==='GET')return send(res,405,{error:'SSE sessions are not enabled; use POST Streamable HTTP.'},{allow:'POST'});
     if(req.method!=='POST')return send(res,405,{error:'Method not allowed'},{allow:'POST'});
     const message=await readJson(req,65536);const reply=await handleMcpMessage(message,{check,feedback:recordFeedback,feedbackAuthorized:feedbackAuthorized(req,feedbackKey)});activityStore.record(req,{kind:'mcp',route:message?.method||null,status:reply===null?202:200});
     if(reply===null){res.writeHead(202,{...baseHeaders,'mcp-protocol-version':MCP_PROTOCOL_VERSION});return res.end();}
     return send(res,200,reply,{'mcp-protocol-version':MCP_PROTOCOL_VERSION});
   }
   if(req.method==='GET'&&u.pathname==='/v1/check'){
     const target=u.searchParams.get('url');if(!target)return send(res,400,{error:'Missing url query parameter',code:'PREFLIGHT_BAD_REQUEST'});
     const key=keyFor(target);const had=await cacheStore.get(key);if(had){const evidence=await feedbackStore.evidence(target);const body=applyRouteFeedback(had,evidence);activityStore.record(req,{kind:'check',route:body.bestRoute,target,status:200});return send(res,200,body,{'x-preflight-cache':'HIT'});}const result=await probe(target);const stored=await cacheStore.put(key,result);const evidence=await feedbackStore.evidence(target);const body=applyRouteFeedback(stored,evidence);activityStore.record(req,{kind:'check',route:body.bestRoute,target,status:200});return send(res,200,body,{'x-preflight-cache':'MISS'});
   }
   if(req.method==='POST'&&u.pathname==='/v1/feedback'){
     if(!feedbackAuthorized(req,feedbackKey))return send(res,401,{error:'Valid bearer token required for feedback',code:'PREFLIGHT_UNAUTHORIZED'});
     const body=await readJson(req);const receipt=await recordFeedback(body);activityStore.record(req,{kind:'feedback',route:body.route,target:body.url,status:202});return send(res,202,receipt);
   }
   return send(res,404,{error:'Not found'});
  }catch(e){const status=e?.code==='PREFLIGHT_UNSAFE_URL'?422:e?.code==='PREFLIGHT_BODY_TOO_LARGE'?413:['PREFLIGHT_BAD_URL','PREFLIGHT_BAD_JSON','PREFLIGHT_BAD_FEEDBACK'].includes(e?.code)?400:500;return send(res,status,{error:e instanceof Error?e.message:'Unknown error',code:e?.code||'PREFLIGHT_INTERNAL'});}});
}
if(process.argv[1]&&new URL(import.meta.url).pathname===process.argv[1]){const server=createServer();const port=Number(process.env.PORT||8080);server.listen(port,process.env.HOST||'0.0.0.0',()=>console.log(`PREFLIGHT ${VERSION} listening on :${port}`));const stop=()=>server.close(()=>process.exit(0));process.on('SIGTERM',stop);process.on('SIGINT',stop);}
